---
title: "Dongnyok Shim"
---

::::::: bio-container
::: bio-tabs
:::

::: korean-info
**건국대학교**

**산업경영융합학부(School of interdisciplinary industrial management)**

✉️ sk4me\@konkuk.ac.kr
:::

::: quote-section
***"혁신 연구자로서 데이터과학을 활용해 하이테크 시장을 분석하고,\
해당 시장에서 기업의 혁신전략과 정부의 혁신정책 전주기를 연구합니다."***
:::

::: detailed-bio
제 연구는 크게 두 가지 축으로 이루어집니다.

-   **첫째, 하이테크 마켓에서 소비자 의사결정 및 선호분석**\
    시장 불확실성과 기술 불확실성이 높은 하이테크 마켓에서 소비자의 선호와 수요를 분석하여 신제품 개발 및 관리에 관한 전략을 수립하는 연구를 수행합니다.

-   **둘째, 기술 환경변화에 따른 기업 및 산업의 대응 정책과 전략**\
    탄소중립, ESG, 기술주권주의, AI기술혁신에 따른 디지털전환 등과 같은 급격한 환경변화로 인해 기업, 산업, 국가 수준에서 새로운 기술전략을 요구받고 있습니다. 환경 변화가 기업 및 국가에 미치는 영향을 정량적으로 분석하고 방향을 모색합니다.
:::
:::::::

## Employment

-   Associate Professor, School of Interdisciplinary Industrial Management, Konkuk University (2024-Present)
-   Assistant Professor, Department of Advanced Industry Fusion, Konkuk University (2020-2024)
-   Assoicate Fellow, KISDI (2018-2020)
-   Researcher, Spri (2017-2018)

## Education

-   Ph.D. in Technology Management Economics and Policy Program, Seoul National University (2016)
-   M.S. in Technology Management Economics and Policy Program, Seoul National University (2012)
-   B.S. in Information and Communication Engineering(Major), IT business (Minor), KAIST (2010)

## Teachings

### Undergraduate

-   Innovation Management and New Product Development
-   Convergence on Digital Industry
-   Consumer Behavior
-   Understanding of Data Science
-   R for Statistical Practice

### Graduate

-   New Product Development
-   Technology Forecasting

## Internal and External Positions

### Internal Position

-   Dean of Graduate school of interdisciplinary industrial management
-   Director, Innovation Strategy and Policy Lab

### External Position

-   Outside Director, [NEXT group](https://nextgroup.or.kr/ko/intro/group/list)

## Achievements

-   Best Paper Award, Korea Innovation Society (2023)
-   Outstanding Research Award, Konkuk University (2023)

{{< include partials/publications.qmd >}}
